"""Add notification and discussion participant tables

Revision ID: 294c806bafa6
Revises: fe4ba02cd2ec
Create Date: 2025-09-13 12:10:33.886784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294c806bafa6'
down_revision = 'fe4ba02cd2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('participant_identifier', sa.String(length=255), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('response_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.create_index('idx_discussion_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_discussion_title_desc', ['title', 'description'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('discussion_participant_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('discussion_response_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('weekly_digest_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('weekly_digest_enabled')
        batch_op.drop_column('discussion_response_notifications')
        batch_op.drop_column('discussion_participant_notifications')
        batch_op.drop_column('email_notifications')

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_index('idx_discussion_title_desc')
        batch_op.drop_index('idx_discussion_created_at')

    op.drop_table('notification')
    op.drop_table('discussion_participant')
    # ### end Alembic commands ###
