"""Add discussion model enhancements

Revision ID: 33cd195c4cfc
Revises: b8db867d35f9
Create Date: 2024-10-31 13:52:07.376023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cd195c4cfc'
down_revision = 'b8db867d35f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.alter_column('embed_code',
               existing_type=sa.VARCHAR(length=800),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.alter_column('embed_code',
               existing_type=sa.VARCHAR(length=800),
               nullable=True)

    # ### end Alembic commands ###
