"""Add location, email, and slug to profiles

Revision ID: 5292f3f8a690
Revises: 04a19e9c96b9
Create Date: 2024-10-26 06:30:06.299580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5292f3f8a690'
down_revision = '04a19e9c96b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))

    with op.batch_alter_table('individual_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual_profile', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('email')
        batch_op.drop_column('location')

    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('email')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
