"""Add email analytics tracking

Revision ID: 615fd0b16628
Revises: 7322ba1f9613
Create Date: 2026-01-07 15:00:03.722211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '615fd0b16628'
down_revision = '7322ba1f9613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_item', schema=None) as batch_op:
        batch_op.alter_column('perspectives',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('daily_brief_subscriber', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['magic_token'])

    with op.batch_alter_table('statement_vote', schema=None) as batch_op:
        batch_op.drop_index('uq_statement_session_vote', postgresql_where='(session_fingerprint IS NOT NULL)')
        batch_op.drop_constraint('uq_statement_user_vote', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_vote', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_statement_user_vote', ['statement_id', 'user_id'])
        batch_op.create_index('uq_statement_session_vote', ['statement_id', 'session_fingerprint'], unique=True, postgresql_where='(session_fingerprint IS NOT NULL)')

    with op.batch_alter_table('daily_brief_subscriber', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('brief_item', schema=None) as batch_op:
        batch_op.alter_column('perspectives',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
