"""add composite index partner_env_created_at on discussion

Revision ID: 837a538b5b96
Revises: b93eca2a3472
Create Date: 2026-02-10 15:52:38.943124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837a538b5b96'
down_revision = 'b93eca2a3472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.create_index('idx_discussion_partner_env_created', ['partner_env', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_index('idx_discussion_partner_env_created')

    # ### end Alembic commands ###
