"""Add keywords field to Discussion model

Revision ID: 85a79dd1848d
Revises: d3fad8d6533c
Create Date: 2024-10-30 09:49:28.677048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a79dd1848d'
down_revision = 'd3fad8d6533c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
