"""Add daily question system tables

Revision ID: 874209e337cc
Revises: b3c3a46418d0
Create Date: 2026-01-02 13:14:19.240480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874209e337cc'
down_revision = 'b3c3a46418d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_date', sa.Date(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('why_this_question', sa.String(length=300), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_discussion_id', sa.Integer(), nullable=True),
    sa.Column('source_statement_id', sa.Integer(), nullable=True),
    sa.Column('source_trending_topic_id', sa.Integer(), nullable=True),
    sa.Column('topic_category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('cold_start_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['source_discussion_id'], ['discussion.id'], ),
    sa.ForeignKeyConstraint(['source_statement_id'], ['statement.id'], ),
    sa.ForeignKeyConstraint(['source_trending_topic_id'], ['trending_topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_date'),
    sa.UniqueConstraint('question_date', name='uq_daily_question_date')
    )
    with op.batch_alter_table('daily_question', schema=None) as batch_op:
        batch_op.create_index('idx_daily_question_date', ['question_date'], unique=False)
        batch_op.create_index('idx_daily_question_status', ['status'], unique=False)

    op.create_table('daily_question_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('vote', sa.SmallInteger(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_question_id'], ['daily_question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_question_id', 'session_fingerprint', name='uq_daily_question_session'),
    sa.UniqueConstraint('daily_question_id', 'user_id', name='uq_daily_question_user')
    )
    with op.batch_alter_table('daily_question_response', schema=None) as batch_op:
        batch_op.create_index('idx_dqr_date', ['created_at'], unique=False)
        batch_op.create_index('idx_dqr_question', ['daily_question_id'], unique=False)
        batch_op.create_index('idx_dqr_user', ['user_id'], unique=False)

    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.drop_index('idx_news_article_fetched')
        batch_op.drop_index('idx_news_article_source_fetched')

    with op.batch_alter_table('trending_topic', schema=None) as batch_op:
        batch_op.drop_index('idx_trending_topic_created')
        batch_op.drop_index('idx_trending_topic_status_hold')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trending_topic', schema=None) as batch_op:
        batch_op.create_index('idx_trending_topic_status_hold', ['status', 'hold_until'], unique=False)
        batch_op.create_index('idx_trending_topic_created', [sa.text('created_at DESC')], unique=False)

    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.create_index('idx_news_article_source_fetched', ['source_id', sa.text('fetched_at DESC')], unique=False)
        batch_op.create_index('idx_news_article_fetched', [sa.text('fetched_at DESC')], unique=False)

    with op.batch_alter_table('daily_question_response', schema=None) as batch_op:
        batch_op.drop_index('idx_dqr_user')
        batch_op.drop_index('idx_dqr_question')
        batch_op.drop_index('idx_dqr_date')

    op.drop_table('daily_question_response')
    with op.batch_alter_table('daily_question', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_question_status')
        batch_op.drop_index('idx_daily_question_date')

    op.drop_table('daily_question')
    # ### end Alembic commands ###
