"""Add audience_score and primary_topic to TrendingTopic

Revision ID: 8fda1aabee9a
Revises: c3a2f6d73e0a
Create Date: 2026-01-01 09:35:35.029101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fda1aabee9a'
down_revision = 'c3a2f6d73e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trending_topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audience_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('primary_topic', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trending_topic', schema=None) as batch_op:
        batch_op.drop_column('primary_topic')
        batch_op.drop_column('audience_score')

    # ### end Alembic commands ###
