"""Update view tracking models and relationships

Revision ID: a6113c110243
Revises: 37714e83f4e9
Create Date: 2024-11-01 12:06:24.109184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6113c110243'
down_revision = '37714e83f4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('individual_profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('company_profile_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('profile_view_profile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'company_profile', ['company_profile_id'], ['id'])
        batch_op.create_foreign_key(None, 'individual_profile', ['individual_profile_id'], ['id'])
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profile_view_profile_id_fkey', 'individual_profile', ['profile_id'], ['id'])
        batch_op.drop_column('company_profile_id')
        batch_op.drop_column('individual_profile_id')

    # ### end Alembic commands ###
