"""Add country to NewsSource and DiscussionSourceArticle table

Revision ID: b3c3a46418d0
Revises: 8fda1aabee9a
Create Date: 2026-01-02 08:49:30.902467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c3a46418d0'
down_revision = '8fda1aabee9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_source_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_article.id'], ),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discussion_id', 'article_id', name='uq_discussion_article')
    )
    with op.batch_alter_table('discussion_source_article', schema=None) as batch_op:
        batch_op.create_index('idx_dsa_article', ['article_id'], unique=False)
        batch_op.create_index('idx_dsa_discussion', ['discussion_id'], unique=False)

    with op.batch_alter_table('news_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))

    # Note: Removed auto-generated index drops for news_article and trending_topic
    # These indexes are needed for query performance in the trending pipeline
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_source', schema=None) as batch_op:
        batch_op.drop_column('country')

    with op.batch_alter_table('discussion_source_article', schema=None) as batch_op:
        batch_op.drop_index('idx_dsa_discussion')
        batch_op.drop_index('idx_dsa_article')

    op.drop_table('discussion_source_article')
    # ### end Alembic commands ###
