"""Add daily question subscriber and selection tracking tables

Revision ID: b63f9c268ab9
Revises: 874209e337cc
Create Date: 2026-01-02 13:30:01.611185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63f9c268ab9'
down_revision = '874209e337cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_question_subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('magic_token', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_participation_date', sa.Date(), nullable=True),
    sa.Column('thoughtful_participations', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_email_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('magic_token')
    )
    with op.batch_alter_table('daily_question_subscriber', schema=None) as batch_op:
        batch_op.create_index('idx_dqs_email', ['email'], unique=False)
        batch_op.create_index('idx_dqs_token', ['magic_token'], unique=False)

    op.create_table('daily_question_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_discussion_id', sa.Integer(), nullable=True),
    sa.Column('source_statement_id', sa.Integer(), nullable=True),
    sa.Column('source_trending_topic_id', sa.Integer(), nullable=True),
    sa.Column('selected_at', sa.DateTime(), nullable=True),
    sa.Column('question_date', sa.Date(), nullable=False),
    sa.Column('daily_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_question_id'], ['daily_question.id'], ),
    sa.ForeignKeyConstraint(['source_discussion_id'], ['discussion.id'], ),
    sa.ForeignKeyConstraint(['source_statement_id'], ['statement.id'], ),
    sa.ForeignKeyConstraint(['source_trending_topic_id'], ['trending_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_question_selection')
    with op.batch_alter_table('daily_question_subscriber', schema=None) as batch_op:
        batch_op.drop_index('idx_dqs_token')
        batch_op.drop_index('idx_dqs_email')

    op.drop_table('daily_question_subscriber')
    # ### end Alembic commands ###
