"""Remove polis_id from Discussion and use embed code instead

Revision ID: b8db867d35f9
Revises: 85a79dd1848d
Create Date: 2024-10-31 10:47:44.941021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8db867d35f9'
down_revision = '85a79dd1848d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion') as batch_op:
        batch_op.add_column(sa.Column('embed_code', sa.String(length=800), nullable=True))
        batch_op.drop_column('polis_id')  # Only drop the column
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion') as batch_op:
        batch_op.add_column(sa.Column('polis_id', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('embed_code')
    # ### end Alembic commands ###
