"""Add missing FK for audio_generation_job brief_run_id

Revision ID: b93eca2a3472
Revises: 2938ecbcf765
Create Date: 2026-02-10 15:24:49.808191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93eca2a3472'
down_revision = '2938ecbcf765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_generation_job', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'brief_run', ['brief_run_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_generation_job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
