"""Add trending topics system tables

Revision ID: c3a2f6d73e0a
Revises: c1a2b3c4d5e6
Create Date: 2025-12-31 19:58:10.285543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a2f6d73e0a'
down_revision = 'c1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('feed_url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('fetch_error_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('news_source', schema=None) as batch_op:
        batch_op.create_index('idx_news_source_active', ['is_active'], unique=False)

    op.create_table('news_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('sensationalism_score', sa.Float(), nullable=True),
    sa.Column('title_embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['news_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_source_article')
    )
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.create_index('idx_article_external_id', ['external_id'], unique=False)
        batch_op.create_index('idx_article_fetched', ['fetched_at'], unique=False)
        batch_op.create_index('idx_article_source', ['source_id'], unique=False)

    op.create_table('trending_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('canonical_tags', sa.JSON(), nullable=True),
    sa.Column('topic_slug', sa.String(length=200), nullable=True),
    sa.Column('civic_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('risk_flag', sa.Boolean(), nullable=True),
    sa.Column('risk_reason', sa.String(length=200), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('topic_embedding', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('hold_until', sa.DateTime(), nullable=True),
    sa.Column('merged_into_topic_id', sa.Integer(), nullable=True),
    sa.Column('merged_into_discussion_id', sa.Integer(), nullable=True),
    sa.Column('seed_statements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('discussion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.id'], ),
    sa.ForeignKeyConstraint(['merged_into_discussion_id'], ['discussion.id'], ),
    sa.ForeignKeyConstraint(['merged_into_topic_id'], ['trending_topic.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trending_topic', schema=None) as batch_op:
        batch_op.create_index('idx_topic_created', ['created_at'], unique=False)
        batch_op.create_index('idx_topic_hold_until', ['hold_until'], unique=False)
        batch_op.create_index('idx_topic_status', ['status'], unique=False)

    op.create_table('trending_topic_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_article.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['trending_topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'article_id', name='uq_topic_article')
    )
    with op.batch_alter_table('trending_topic_article', schema=None) as batch_op:
        batch_op.create_index('idx_tta_article', ['article_id'], unique=False)
        batch_op.create_index('idx_tta_topic', ['topic_id'], unique=False)

    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.create_index('idx_company_profile_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.alter_column('has_native_statements',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_index('ix_discussion_creator_created')
        batch_op.drop_index('ix_discussion_topic_country')
        batch_op.create_index('idx_discussion_creator_id', ['creator_id'], unique=False)
        batch_op.create_index('idx_discussion_is_featured', ['is_featured'], unique=False)
        batch_op.create_index('idx_discussion_topic', ['topic'], unique=False)

    with op.batch_alter_table('discussion_participant', schema=None) as batch_op:
        batch_op.drop_index('ix_discussion_participant_activity')
        batch_op.drop_index('ix_discussion_participant_discussion')
        batch_op.drop_index('ix_discussion_participant_user')
        batch_op.drop_constraint('uq_discussion_participant_identifier', type_='unique')

    with op.batch_alter_table('individual_profile', schema=None) as batch_op:
        batch_op.create_index('idx_individual_profile_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_discussion_created')
        batch_op.drop_index('ix_notification_type')
        batch_op.drop_index('ix_notification_user_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_notification_type', ['type'], unique=False)
        batch_op.create_index('ix_notification_discussion_created', ['discussion_id', 'created_at'], unique=False)

    with op.batch_alter_table('individual_profile', schema=None) as batch_op:
        batch_op.drop_index('idx_individual_profile_user_id')

    with op.batch_alter_table('discussion_participant', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_discussion_participant_identifier', ['discussion_id', 'participant_identifier'])
        batch_op.create_index('ix_discussion_participant_user', ['user_id'], unique=False)
        batch_op.create_index('ix_discussion_participant_discussion', ['discussion_id'], unique=False)
        batch_op.create_index('ix_discussion_participant_activity', ['last_activity'], unique=False)

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_index('idx_discussion_topic')
        batch_op.drop_index('idx_discussion_is_featured')
        batch_op.drop_index('idx_discussion_creator_id')
        batch_op.create_index('ix_discussion_topic_country', ['topic', 'country'], unique=False)
        batch_op.create_index('ix_discussion_creator_created', ['creator_id', 'created_at'], unique=False)
        batch_op.alter_column('has_native_statements',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.drop_index('idx_company_profile_user_id')

    with op.batch_alter_table('trending_topic_article', schema=None) as batch_op:
        batch_op.drop_index('idx_tta_topic')
        batch_op.drop_index('idx_tta_article')

    op.drop_table('trending_topic_article')
    with op.batch_alter_table('trending_topic', schema=None) as batch_op:
        batch_op.drop_index('idx_topic_status')
        batch_op.drop_index('idx_topic_hold_until')
        batch_op.drop_index('idx_topic_created')

    op.drop_table('trending_topic')
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.drop_index('idx_article_source')
        batch_op.drop_index('idx_article_fetched')
        batch_op.drop_index('idx_article_external_id')

    op.drop_table('news_article')
    with op.batch_alter_table('news_source', schema=None) as batch_op:
        batch_op.drop_index('idx_news_source_active')

    op.drop_table('news_source')
    # ### end Alembic commands ###
