"""Add individual social media fields to profiles

Revision ID: e0ccc49c9b2d
Revises: b47d501d3cd7
Create Date: 2024-10-29 09:49:01.638025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0ccc49c9b2d'
down_revision = 'b47d501d3cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('social_links')

    with op.batch_alter_table('individual_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('social_links')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('tiktok_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('linkedin_url')

    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('tiktok_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('linkedin_url')

    # ### end Alembic commands ###
