"""add_social_post_engagement_table

Revision ID: fd7bceb76f95
Revises: b6c7d8e9f0g1
Create Date: 2026-01-14 13:11:57.997075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd7bceb76f95'
down_revision = 'b6c7d8e9f0g1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_post_engagement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('post_id', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('hook_variant', sa.String(length=50), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('reposts', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('quotes', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'post_id', name='uq_platform_post_id')
    )
    with op.batch_alter_table('social_post_engagement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_post_engagement_discussion_id'), ['discussion_id'], unique=False)

    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('daily_brief', schema=None) as batch_op:
        batch_op.alter_column('lens_check',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('daily_question_response', schema=None) as batch_op:
        batch_op.drop_index('idx_dqr_email_question')

    with op.batch_alter_table('daily_question_subscriber', schema=None) as batch_op:
        batch_op.drop_index('idx_dqs_unsubscribe_reason')

    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.drop_index('idx_article_published_source')

    with op.batch_alter_table('news_perspective_cache', schema=None) as batch_op:
        batch_op.alter_column('generated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_index('idx_response_session_fingerprint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.create_index('idx_response_session_fingerprint', ['session_fingerprint'], unique=False)

    with op.batch_alter_table('news_perspective_cache', schema=None) as batch_op:
        batch_op.alter_column('generated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.create_index('idx_article_published_source', [sa.text('published_at DESC'), 'source_id'], unique=False)

    with op.batch_alter_table('daily_question_subscriber', schema=None) as batch_op:
        batch_op.create_index('idx_dqs_unsubscribe_reason', ['unsubscribe_reason'], unique=False)

    with op.batch_alter_table('daily_question_response', schema=None) as batch_op:
        batch_op.create_index('idx_dqr_email_question', ['email_question_id'], unique=False)

    with op.batch_alter_table('daily_brief', schema=None) as batch_op:
        batch_op.alter_column('lens_check',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('social_post_engagement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_post_engagement_discussion_id'))

    op.drop_table('social_post_engagement')
    # ### end Alembic commands ###
